- name: Ensure storage_meta directory exists
  ansible.builtin.file:
    path: "{{ repo_dest }}"
    state: directory

- name: Ensure the Docker container is stopped
  community.docker.docker_container:
    name: "{{ iphone_docker_image }}"
    state: stopped
  ignore_errors: true

- name: Render iphone.conf from template
  ansible.builtin.template:
    src: ../storage_meta/iphone.conf.j2  # Path to your Jinja2 template for Nginx config
    dest: /tmp/iphone.conf


- name: Create Docker container with Apache
  community.docker.docker_container:
    name: "{{ iphone_docker_image }}"
    image: "{{ apache_docker_image_name }}"
    ports:
      - "{{ iphone_exposed_port }}:{{ iphone_internal_port }}"
    networks:
      - name: bridge_network
    volumes:
      - "{{ iphone_host_storage_directory }}:{{ iphone_container_storage_directory }}"
      - /tmp/iphone.conf:/etc/apache2/sites-available/iphone.conf
    state: started

- name: Wait for Docker container to be running
  community.docker.docker_container_info:
    name: "{{ iphone_docker_image }}"
  register: docker_info
  retries: 2
  delay: 5
  until: docker_info.container.State.Running == true
  ignore_errors: false

- name: Remove default Apache configs
  community.docker.docker_container_exec:
    container: "{{ iphone_docker_image }}"
    command: |
      sh -c 'rm -rf /var/www/html/ /etc/apache2/sites-enabled/* /etc/apache2/sites-available/* /etc/apache2/conf-enabled/* /etc/apache2/conf-available/*'

- name: Reload Apache
  community.docker.docker_container_exec:
    container: "{{ iphone_docker_image }}"
    command: "service apache2 reload"
