# Adds entry for main cloud in ssh_config e.g., to be able to ssh kaxtus
- name: Get actual user home directory
  become: no
  ansible.builtin.set_fact:
    actual_home: "{{ lookup('env', 'HOME') }}"

- name: Configure SSH alias for {{ ssh_host_name }}
  ansible.builtin.lineinfile:
    path: "{{ actual_home }}/.ssh/config"
    create: true
    line: "{{ item }}"
    state: present
    mode: '0600'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  loop:
    - "Host {{ ssh_host_name }}"
    - "    HostName {{ cloud_ip }}"
    - "    User ubuntu"
    - "    ForwardAgent yes"
