- name: Setup Docker bridge network and configure containers
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - ../../vars/all.yaml
  tasks:
    - name: Remove existing Docker bridge network if it exists
      docker_network:
        name: "{{ bridge_network_name }}"
        state: absent
      ignore_errors: yes

    - name: Create a Docker bridge network
      docker_network:
        name: "{{ bridge_network_name }}"
        driver: bridge
        state: present