- name: Pull Docker image
  docker_image:
    name: "{{ docker_image }}"
    tag: "{{ docker_tag }}"
    source: pull
    force_source: yes
    state: present

- name: Create download directory
  file:
    path: "{{ output_dir }}"
    state: directory
    mode: '0755'

- name: Stop existing container
  docker_container:
    name: "{{ container_name }}"
    state: absent
  ignore_errors: yes

- name: Run Docker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}:{{ docker_tag }}"
    state: started
    recreate: yes
    restart_policy: unless-stopped
    ports:
      - "{{ host_port }}:{{ app_port }}"
    volumes:
      - "{{ output_dir }}:/app/downloads"
    env:
      PORT: "{{ app_port }}"
      OUTPUT_DIR: "/app/downloads"
      TEMP_DIR: "{{ temp_dir }}"
      MAX_FILE_SIZE: "{{ max_file_size }}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:{{ app_port }}/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s