- name: Install Docker if not installed
  block:
    # ... previous Docker installation tasks ...

    - name: Create docker group if it doesn't exist
      ansible.builtin.group:
        name: docker
        state: present
      become: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user | default(ansible_env.USER) }}"
        groups: docker
        append: yes
      become: yes

    - name: Fix Docker socket permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'
        group: docker
      become: yes

    - name: Ensure Docker directory permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        group: docker
        recurse: yes
      become: yes
      loop:
        - /var/run/docker
        - /var/lib/docker

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
      become: yes

    - name: Force group membership update without logout
      ansible.builtin.shell: |
        sudo chmod 666 /var/run/docker.sock
        newgrp docker
      become: yes

    - name: Reset SSH connection to apply new group
      ansible.builtin.meta: reset_connection

    - name: Wait for Docker socket to be accessible
      ansible.builtin.wait_for:
        path: /var/run/docker.sock
        timeout: 30

  when: docker_check.rc != 0

- name: Display Docker setup completion message
  ansible.builtin.debug:
    msg: |
      Docker setup is complete. 
      If you still see permission errors, try these manual steps:
      1. Log out and log back in, or
      2. Run these commands:
         sudo chmod 666 /var/run/docker.sock
         newgrp docker