# Creates a docker container for website kaxtus
# Must use bridge first see cloud
- name: Ensure storage_meta directory exists
  ansible.builtin.file:
    path: "{{ repo_dest }}"
    state: directory

- name: Display SSH key addition instructions
  ansible.builtin.debug:
    msg: |
      ⚠️ If git clone fails, you need to add SSH keys forwarding

- name: Ensure the Docker container is stopped
  community.docker.docker_container:
    name: "{{ homepage_docker_image }}"
    state: stopped
  ignore_errors: true

- name: Clone the repository
  ansible.builtin.git:
    repo: "{{ homepage_repo_url }}"
    dest: "{{ repo_dest }}/homePage"
    update: yes
    force: yes
  register: git_result
  ignore_errors: true

- name: Show Git error if clone failed
  ansible.builtin.debug:
    msg: |
      Git clone failed. Please ensure:
      1. Your SSH key is added to GitHub
      2. Your SSH key is on the remote host
      3. Try manually: ssh -T git@github.com
      
      Error was: {{ git_result.msg }}
  when: git_result.failed

- name: Create Docker container with Apache
  community.docker.docker_container:
    name: "{{ homepage_docker_image }}"
    image: "ubuntu/apache2"
    ports:
      - "{{ homepage_exposed_port }}:{{ homepage_internal_port }}"
    networks:
      - name: "{{ bridge_network_name }}"
    volumes:
      - "{{ homepage_host_directory }}:{{ homepage_container_dist_directory }}:ro"
    state: started
  when: not git_result.failed

- name: Wait for Apache to start
  ansible.builtin.wait_for:
    port: "{{ homepage_exposed_port }}"
    timeout: 30
  when: not git_result.failed

- name: Print completion message
  ansible.builtin.debug:
    msg: "Apache Docker container ubuntu/apache2 is running and serving content from './{{ homepage_host_directory }}'."
  when: not git_result.failed