- name: Deploy Apache Docker Container with Homepage
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  tasks:
    - name: Ensure storage_meta directory exists
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: directory

    - name: Ensure the Docker container is stopped
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: stopped
      ignore_errors: true

    - name: Clone the repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}/homePage"
        update: yes
        force: yes

    - name: Create Docker container with Apache
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        ports:
          - "{{ exposed_port }}:80"
        volumes:
          - "{{ host_directory }}:{{ container_directory }}:ro"
        state: started

    - name: Wait for Apache to start
      ansible.builtin.wait_for:
        port: "{{ exposed_port }}"
        timeout: 30

    - name: Print completion message
      ansible.builtin.debug:
        msg: "Apache Docker container '{{ docker_container_name }}' is running and serving content from './{{ host_directory }}'."
