- name: Configure Nginx for kaxtus.com
  hosts: kaxtus
  become: yes
  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create Nginx configuration for kaxtus.com
      copy:
        dest: /etc/nginx/sites-available/kaxtus.com
        content: |
          server {
              listen 80;
              server_name kaxtus.com;

              location / {
                  proxy_pass http://localhost:85;  # Forward traffic to port 85
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        owner: root
        group: root
        mode: '0644'

    - name: Enable Nginx site for kaxtus.com
      file:
        src: /etc/nginx/sites-available/kaxtus.com
        dest: /etc/nginx/sites-enabled/kaxtus.com
        state: link

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0