- name: Configure Nginx for kaxtus.com
  hosts: kaxtus
  become: yes
  vars_files:
    - ../group_vars/all.yaml
  tasks:
  - name: Ensure Docker is installed
    ansible.builtin.package:
      name: "{{ docker_package }}"
      state: present
    vars:
      docker_package: "{{ 'docker.io' if ansible_os_family == 'Debian' else 'docker' }}"

  - name: Ensure Docker service is running
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes
  - name: Stop and remove existing Nginx container (if any)
    ansible.builtin.docker_container:
      name: nginx-container
      state: absent  # Stop and remove the container if it's already present
      force_kill: yes  # Forcefully stop the container if it's running

  - name: Pull the Nginx Docker image
    ansible.builtin.docker_image:
      name: nginx
      source: pull

  - name: Render nginx.conf from template
    ansible.builtin.template:
      src: ../storage_meta/nginx.conf.j2  # Path to your Jinja2 template for Nginx config
      dest: /tmp/nginx.conf  # Destination on the host machine

  - name: Run the Nginx container
    ansible.builtin.docker_container:
      name: nginx-container
      image: nginx
      state: started
      networks:
        - name: bridge_network
      ports:
        - "80:80"
      volumes:
        - /tmp/nginx.conf:/etc/nginx/nginx.conf  # Mount the rendered config file inside the container


  - name: Reload Nginx configuration
    ansible.builtin.command:
      cmd: docker exec nginx-container nginx -s reload