- name: Update Git repository
  hosts: localhost  # Or specify a host if you want it to run on a remote machine
  become: no
  tasks:
    - name: Add changes to git
      command:
        cmd: git add ../.

    - name: Commit changes to git
      command:
        cmd: git commit -m "Automated commit via Ansible"

    - name: Push changes to git
      command:
        cmd: git push origin main
