- name: Set the port and username for localhost
  set_fact:
    docker_image_name: "{{ websites[website].docker_image_name }}"
    repo_url: "{{ websites[website].repo_url }}"
    root_name: "{{ websites[website].root_name }}"
    in_port: "{{ websites[website].in_port }}"
    ex_port: "{{ websites[website].ex_port }}"
    bin_dir: "{{ websites_cloud_dir }}/{{ websites[website].root_name }}/{{ websites[website].bin_dir }}"

- name: Ensure storage_meta directory exists
  ansible.builtin.file:
    path: "{{ websites_cloud_dir }}"
    state: directory

- name: Ensure the Docker container is stopped
  community.docker.docker_container:
    name: "{{ docker_image_name }}"
    state: stopped
  ignore_errors: true

- name: Clone the repository
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ websites_cloud_dir }}/{{ root_name }}"
    update: yes
    force: yes

- name: Create Docker container with Apache
  community.docker.docker_container:
    name: "{{ docker_image_name }}"
    image: "ubuntu/apache2"
    ports:
      - "{{ ex_port }}:{{ in_port }}"
    networks:
      - name: "{{ bridge_network_name }}"
    volumes:
      - "{{ bin_dir }}:{{ apache_ubuntu_image_default_page_dir }}"
    state: started

- name: Wait for Apache to start
  ansible.builtin.wait_for:
    port: "{{ ex_port }}"
    timeout: 30

- name: Print completion message
  ansible.builtin.debug:
    msg: "Apache Docker container ubuntu/apache2 is running and serving content from './{{ bin_dir }}'."
