websites:
  kaxtus:
      domains: ['kaxtus.com', 'www.kaxtus.com']
      repo_url: 'git@github.com:kaxtus/homePage.git'
      docker_image_name: 'kaxtus-website'
      root_name: 'kaxtus-website'
      bin_dir: 'dist'
      ssl_enabled: true
      ssl_email: "admin@kaxtus.com"
  gaspi:
      domains: ['gaspi.aero', 'www.gaspi.aero']
      repo_url: 'git@github.com:OverDriveGain/gaspi.git'
      docker_image_name: 'gaspi-website'
      root_name: 'gaspi-website'
      port: 10081
      app_js_dir: 'formserver'
      ssl_enabled: true
      ssl_email: "admin@gaspi.aero"
  calgaryexpedite:
      domains: ['calgaryexpedite.com', 'www.calgaryexpedite.com']
      repo_url: 'git@github.com:OverDriveGain/calgaryexpedite.git'
      docker_image_name: 'calgaryexpedite-website'
      root_name: 'calgaryexpedite-website'
      port: 10084
      app_js_dir: 'formserver'
      ssl_enabled: true
      ssl_email: "admin@calgaryexpedite.com"
  music:
      domains: ['music.kaxtus.com']
      port: 10082
      app_secret: supersecret
      container_name: leafplayer
      admin_username: admin
      admin_password: supersecret
      ssl_enabled: true
      ssl_email: "admin@kaxtus.com"
      users: ['manar', 'mike']
  house:
      domains: ['house.zaboub.com']
      port: 8123
      ssl_enabled: true
      ssl_email: "manar@zaboub.com"
      nginx_proxy_headers:
          upgrade: "$http_upgrade"
          connection: "upgrade"
  quotomate:
      domains: [ 'quotomate.com', 'www.quotomate.com' ]
      repo_url: 'git@github.com:OverDriveGain/quotomate-web.git'
      docker_image_name: 'quotomate-website'
      root_name: 'quotomate-website'
      port: 10083
      app_js_dir: 'backend'
      ssl_enabled: true
      ssl_email: "admin@quotomate.aero"
      unsafe_eval: true
  n8n:
      domains: [ 'n8n.kaxtus.com' ]
      port: 5678
      container_name: n8n
      ssl_enabled: true
      ssl_email: "admin@kaxtus.com"
      websocket_support: true
      websocket_paths:
          - /rest/push
      debug_logging: true
  reiddt:
      domains: [ 'www.reiddt.com' ]
      port: 5679
      container_name: n8n
      ssl_enabled: true
      ssl_email: "admin@kaxtus.com"
