websites:
  kaxtus:
      domains: ['kaxtus.com', 'www.kaxtus.com']
      repo_url: 'git@github.com:kaxtus/homePage.git'
      docker_image_name: 'kaxtus-website'
      root_name: 'kaxtus-website'
      bin_dir: 'dist'
      in_port: 80
      ex_port: 85
  gaspi:
      domains: ['gaspi.aero', 'www.gaspi.aero']
      repo_url: 'git@github.com:OverDriveGain/gaspi.git'
      docker_image_name: 'gaspi-website'
      root_name: 'gaspi-website'
      bin_dir: '.output/public'
      in_port: 80
      ex_port: 86
      app_js_dir: 'formserver'