websites:
  kaxtus:
      domains: ['kaxtus.com', 'www.kaxtus.com']
      repo_url: 'git@github.com:kaxtus/homePage.git'
      docker_image_name: 'kaxtus-website'
      root_name: 'kaxtus-website'
      bin_dir: 'dist'
      ssl_enabled: true
      ssl_email: "admin@kaxtus.com"
  gaspi:
      domains: ['gaspi.aero', 'www.gaspi.aero']
      repo_url: 'git@github.com:OverDriveGain/gaspi.git'
      docker_image_name: 'gaspi-website'
      root_name: 'gaspi-website'
      port: 10081
      app_js_dir: 'formserver'
      ssl_enabled: true
      ssl_email: "admin@gaspi.aero"
